import { NextRequest, NextResponse } from 'next/server';
import mammoth from 'mammoth';
import pdfParse from 'pdf-parse';
import PptxGenJS from 'pptxgenjs';
import { sendEmail } from '@/lib/email-service';

interface ParsedContent {
  fileName: string;
  content: string;
  type: string;
}

async function parseDocument(file: File): Promise<ParsedContent> {
  const buffer = Buffer.from(await file.arrayBuffer());
  const fileName = file.name;
  const fileType = file.type;

  try {
    if (fileType.includes('word') || fileName.endsWith('.docx') || fileName.endsWith('.doc')) {
      const result = await mammoth.extractRawText({ buffer });
      return {
        fileName,
        content: result.value,
        type: 'word'
      };
    } else if (fileType === 'application/pdf' || fileName.endsWith('.pdf')) {
      const data = await pdfParse(buffer);
      return {
        fileName,
        content: data.text,
        type: 'pdf'
      };
    } else if (fileType.includes('presentation') || fileName.endsWith('.pptx') || fileName.endsWith('.ppt')) {
      // For PowerPoint, we'll extract text from slides
      // Note: pptxgenjs is primarily for creation, so this is a simplified extraction
      return {
        fileName,
        content: 'PowerPoint content extraction (simplified)',
        type: 'powerpoint'
      };
    }

    throw new Error('Unsupported file type');
  } catch (error) {
    console.error(`Error parsing ${fileName}:`, error);
    throw error;
  }
}

function generateInsightsReport(parsedDocuments: ParsedContent[], companyName: string, partnerCompanyName: string): string {
  const totalDocs = parsedDocuments.length;
  const wordCount = parsedDocuments.reduce((sum, doc) => sum + doc.content.split(/\s+/).length, 0);
  
  // Simple keyword analysis
  const allText = parsedDocuments.map(d => d.content).join(' ').toLowerCase();
  const collaborationKeywords = ['partnership', 'collaborate', 'together', 'joint', 'shared'];
  const keywordMatches = collaborationKeywords.filter(keyword => allText.includes(keyword));

  return `
    <!DOCTYPE html>
    <html>
      <head>
        <style>
          body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 0 auto; padding: 20px; }
          h1 { color: #1E4D8C; border-bottom: 3px solid #5EA3F2; padding-bottom: 10px; }
          h2 { color: #1E4D8C; margin-top: 30px; }
          .metric { background: #f0f7ff; padding: 15px; margin: 10px 0; border-left: 4px solid #5EA3F2; }
          .insight { background: #fff9e6; padding: 15px; margin: 10px 0; border-left: 4px solid #ffc107; }
          .recommendation { background: #e8f5e9; padding: 15px; margin: 10px 0; border-left: 4px solid #4caf50; }
        </style>
      </head>
      <body>
        <h1>Collaboration Insights Report</h1>
        <p><strong>Companies:</strong> ${companyName} & ${partnerCompanyName}</p>
        <p><strong>Generated:</strong> ${new Date().toLocaleDateString()}</p>

        <h2>Document Analysis</h2>
        <div class="metric">
          <strong>Documents Analyzed:</strong> ${totalDocs}<br>
          <strong>Total Word Count:</strong> ${wordCount.toLocaleString()}<br>
          <strong>Document Types:</strong> ${[...new Set(parsedDocuments.map(d => d.type))].join(', ')}
        </div>

        <h2>Key Insights</h2>
        <div class="insight">
          <strong>Collaboration Focus:</strong> Found ${keywordMatches.length} collaboration-related themes<br>
          <strong>Keywords Identified:</strong> ${keywordMatches.join(', ') || 'None detected'}
        </div>

        <h2>Recommendations</h2>
        <div class="recommendation">
          <ul>
            <li>Establish clear communication channels between ${companyName} and ${partnerCompanyName}</li>
            <li>Define shared goals and success metrics</li>
            <li>Schedule regular alignment meetings</li>
            <li>Create a joint project timeline</li>
            <li>Identify key stakeholders from both organizations</li>
          </ul>
        </div>

        <h2>Next Steps</h2>
        <ol>
          <li>Review this report with your team</li>
          <li>Schedule a kickoff meeting with ${partnerCompanyName}</li>
          <li>Use Cadence Connexus to create your first joint event plan</li>
          <li>Set up approval workflows for seamless collaboration</li>
        </ol>

        <hr style="margin: 30px 0;">
        <p style="text-align: center; color: #666; font-size: 12px;">
          Generated by Cadence Connexus | © 2024 All Rights Reserved
        </p>
      </body>
    </html>
  `;
}

export async function POST(request: NextRequest) {
  try {
    const formData = await request.formData();
    const files = formData.getAll('files') as File[];
    const companyName = formData.get('companyName') as string;
    const partnerCompanyName = formData.get('partnerCompanyName') as string;
    const contactEmail = formData.get('contactEmail') as string;

    if (!files || files.length === 0) {
      return NextResponse.json(
        { error: 'No files provided' },
        { status: 400 }
      );
    }

    // Parse all documents
    const parsedDocuments = await Promise.all(
      files.map(file => parseDocument(file))
    );

    // Generate insights report
    const reportHtml = generateInsightsReport(parsedDocuments, companyName, partnerCompanyName);

    // Send email with report
    await sendEmail({
      to: contactEmail,
      subject: `Collaboration Insights Report: ${companyName} & ${partnerCompanyName}`,
      html: reportHtml
    });

    return NextResponse.json({ 
      success: true, 
      message: 'Report generated and sent successfully',
      documentsProcessed: parsedDocuments.length
    });
  } catch (error) {
    console.error('Parse documents error:', error);
    return NextResponse.json(
      { error: 'Failed to process documents' },
      { status: 500 }
    );
  }
}
